<!-- Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ -->
<script setup>
import {onMounted,reactive,ref} from 'vue';import {request} from '../api'
const rows=ref([]),dashboard=ref(null),error=ref('')
const form=reactive({batchNo:'REC-'+Date.now(),organizationCode:'ZH-SH',counterparty:'示例结算伙伴',sourceAmount:100000,ledgerAmount:99950,transactionCount:1000,matchedCount:1000,unresolvedExceptions:0,counterpartConfirmed:true,invoiceReady:true,bankAccountVerified:true})
async function load(){try{[rows.value,dashboard.value]=await Promise.all([request('/api/settlement/reconciliation'),request('/api/settlement/reconciliation/dashboard')])}catch(e){error.value=e.message}}
async function create(){try{await request('/api/settlement/reconciliation',{method:'POST',body:JSON.stringify(form)});form.batchNo='REC-'+Date.now();await load()}catch(e){error.value=e.message}}
async function act(i,a){if(!confirm('确认'+a+' '+i.batchNo+'？'))return;try{if(a==='自动匹配')await request(`/api/settlement/reconciliation/${i.id}/match`,{method:'POST'});if(a==='复核差异')await request(`/api/admin/settlement/reconciliation/${i.id}/resolve`,{method:'POST',body:JSON.stringify({ledgerAmount:i.sourceAmount,matchedCount:i.transactionCount,unresolvedExceptions:0,remark:'差异凭证复核完成'})});if(a==='确认结算')await request(`/api/settlement/reconciliation/${i.id}/confirm`,{method:'POST'});if(a==='付款结算')await request(`/api/settlement/reconciliation/${i.id}/settle?paymentReference=${encodeURIComponent('PAY-'+i.batchNo)}`,{method:'POST'});await load()}catch(e){error.value=e.message}}
onMounted(load)
</script>
<template><section class="head"><div><span>RECONCILIATION OPERATIONS</span><h3>对账与结算工作台</h3><p>业务源与账务金额核对、交易匹配、差异复核、对方确认、发票和账户付款门禁。</p></div><b>差异闭环</b></section><p v-if="error" class="error" @click="error=''">{{error}} ×</p>
<section v-if="dashboard" class="metrics"><article><span>对账批次</span><b>{{dashboard.total}}</b></article><article><span>差异批次</span><b>{{dashboard.exception}}</b></article><article><span>已确认</span><b>{{dashboard.confirmed}}</b></article><article><span>已结算</span><b>{{dashboard.settled}}</b></article></section>
<form class="card form" @submit.prevent="create"><label>批次号<input v-model="form.batchNo" required></label><label>组织<input v-model="form.organizationCode" required></label><label class="wide">结算伙伴<input v-model="form.counterparty" required></label><label>业务源金额<input v-model.number="form.sourceAmount" type="number" min="0"></label><label>账务金额<input v-model.number="form.ledgerAmount" type="number" min="0"></label><label>交易数<input v-model.number="form.transactionCount" type="number" min="0"></label><label>匹配数<input v-model.number="form.matchedCount" type="number" min="0"></label><label>未决差异<input v-model.number="form.unresolvedExceptions" type="number" min="0"></label><label class="check"><input v-model="form.counterpartConfirmed" type="checkbox">对方已确认</label><label class="check"><input v-model="form.invoiceReady" type="checkbox">发票齐备</label><label class="check"><input v-model="form.bankAccountVerified" type="checkbox">账户已验证</label><button>创建对账批次</button></form>
<section class="card table"><table><thead><tr><th>批次</th><th>金额差异</th><th>匹配情况</th><th>结算门禁</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="i in rows"><td><b>{{i.batchNo}}</b><small>{{i.organizationCode}} · {{i.counterparty}}</small></td><td>{{Math.abs(i.sourceAmount-i.ledgerAmount).toFixed(2)}}<small>{{i.sourceAmount}} / {{i.ledgerAmount}}</small></td><td>{{i.matchedCount}} / {{i.transactionCount}}<small>未决 {{i.unresolvedExceptions}}</small></td><td>{{i.counterpartConfirmed?'已确认':'未确认'}}<small>发票 {{i.invoiceReady?'✓':'×'}} · 账户 {{i.bankAccountVerified?'✓':'×'}}</small></td><td>{{i.state}}</td><td><button v-if="i.state==='DRAFT'" class="text" @click="act(i,'自动匹配')">匹配</button><button v-if="i.state==='EXCEPTION'" class="text" @click="act(i,'复核差异')">复核</button><button v-if="i.state==='RECONCILED'" class="text" @click="act(i,'确认结算')">确认</button><button v-if="i.state==='CONFIRMED'" class="text" @click="act(i,'付款结算')">结算</button></td></tr></tbody></table></section></template>
<style scoped>.head{display:flex;justify-content:space-between;align-items:end;background:#fff;border:1px solid #dce2df;padding:24px 28px;margin-bottom:16px}.head span{font-size:11px;letter-spacing:.16em;color:#b47c2f}.head h3{font-size:24px;margin:5px 0}.head p{margin:0;color:#68777c}.head>b{color:#235a74}.metrics{margin-bottom:16px}.card{background:#fff;border:1px solid #dce2df;padding:20px;margin-bottom:16px}.form{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.form label{display:grid;gap:5px;font-size:12px;color:#68777c}.form input{border:1px solid #ccd6d2;padding:9px}.form .wide{grid-column:span 2}.check{display:flex!important;align-items:center;gap:7px}.check input{width:17px}.form button{border:0;background:#235a74;color:#fff;font-weight:700}.table{padding:0;overflow:auto}.table table{min-width:900px}td small{display:block;color:#68777c}.text{border:0;background:transparent;color:#235a74;padding:4px}.error{color:#a03f38}@media(max-width:900px){.form{grid-template-columns:1fr}.form .wide{grid-column:auto}}</style>
